server:
  port: 6002   #项目端口
spring:
  application:
    name: eureka-server6002  #应用名称
  security:   #注册到eureka需要用户名和密码
    user:
      name: admin
      password: 123

eureka:
  instance:
    hostname: eureka2.com
  server:
    enable-self-preservation: false        #禁用保护,默认true
    eviction-interval-timer-in-ms: 10000    #清理间隔（默认是60*1000）
  client:
    fetch-registry: true #是否向eureka server获取列表信息
    register-with-eureka: true #是否向自己注册
    service-url:
      defaultZone: http://admin:123@eureka1.com:6001/eureka/     #注册地址
