server:
  port: 8088
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry
  protocol:
    name: dubbo
    port: 20888
  provider:
    retries: 2
    timeout: 3000


mybatis-plus:
  type-aliases-package: com.cssl.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test?serverTimezone=GMT
    username: root
    password: root